// AUTO-GENERATED — refreshed by the 2026-06-17 per-provider free-tier research pass.
// Source: _tasks/features-v3.8.28/free-tier-research-2026-06-17.raw.json (50-agent web research + adversarial verification).
// Methodology: honest pool-deduped recurring tokens. "recurring-uncapped" = permanently free but no
// published token cap (rate/concurrency-limited) — NOT summed into the steady headline (see freeModelCatalog.js).
// Deposit-unlock boosts (e.g. OpenRouter $10 -> 1000 RPD) live in FREE_TIER_BOOSTS, not per-record.
// Do not edit by hand — re-run the patch generator to refresh.

export const FREE_MODEL_BUDGETS = [
  { provider: "agentrouter", modelId: "claude-opus-4-6", displayName: "Claude 4.6 Opus", monthlyTokens: 0, creditTokens: 200000000, freeType: "one-time-initial", poolKey: "agentrouter", tos: "caution" },
  { provider: "agentrouter", modelId: "claude-haiku-4-5-20251001", displayName: "Claude 4.5 Haiku", monthlyTokens: 0, creditTokens: 200000000, freeType: "one-time-initial", poolKey: "agentrouter", tos: "caution" },
  { provider: "agentrouter", modelId: "glm-5.1", displayName: "GLM 5.1", monthlyTokens: 0, creditTokens: 200000000, freeType: "one-time-initial", poolKey: "agentrouter", tos: "caution" },
  { provider: "agentrouter", modelId: "deepseek-v3.2", displayName: "DeepSeek V3.2", monthlyTokens: 0, creditTokens: 200000000, freeType: "one-time-initial", poolKey: "agentrouter", tos: "caution" },
  { provider: "agentrouter", modelId: "gpt-4.1-mini", displayName: "GPT 4.1 Mini", monthlyTokens: 0, creditTokens: 200000000, freeType: "one-time-initial", poolKey: "agentrouter", tos: "caution" },
  { provider: "agentrouter", modelId: "gpt-4.1-nano", displayName: "GPT 4.1 Nano", monthlyTokens: 0, creditTokens: 200000000, freeType: "one-time-initial", poolKey: "agentrouter", tos: "caution" },
  { provider: "agentrouter", modelId: "gemini-2.5-flash", displayName: "Gemini 2.5 Flash", monthlyTokens: 0, creditTokens: 200000000, freeType: "one-time-initial", poolKey: "agentrouter", tos: "caution" },
  { provider: "agentrouter", modelId: "gemini-2.5-pro", displayName: "Gemini 2.5 Pro", monthlyTokens: 0, creditTokens: 200000000, freeType: "one-time-initial", poolKey: "agentrouter", tos: "caution" },
  { provider: "agentrouter", modelId: "grok-3", displayName: "Grok 3", monthlyTokens: 0, creditTokens: 200000000, freeType: "one-time-initial", poolKey: "agentrouter", tos: "caution" },
  { provider: "agentrouter", modelId: "claude-sonnet-4-20250514", displayName: "Claude Sonnet 4", monthlyTokens: 0, creditTokens: 200000000, freeType: "one-time-initial", poolKey: "agentrouter", tos: "caution" },
  { provider: "google-ai-studio", modelId: "gemini-2.5-flash", displayName: "Gemini 2.5 Flash", monthlyTokens: 1500000000, creditTokens: 0, freeType: "recurring-monthly", poolKey: "google-ai-studio", tos: "ok" },
  { provider: "google-ai-studio", modelId: "gemini-2.5-pro", displayName: "Gemini 2.5 Pro", monthlyTokens: 150000000, creditTokens: 0, freeType: "recurring-monthly", poolKey: "google-ai-studio", tos: "ok" },
  { provider: "google-ai-studio", modelId: "gemini-2.0-flash", displayName: "Gemini 2.0 Flash", monthlyTokens: 1500000000, creditTokens: 0, freeType: "recurring-monthly", poolKey: "google-ai-studio", tos: "ok" },
  { provider: "google-ai-studio", modelId: "gemma-3-27b-it", displayName: "Gemma 3 27B", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "openrouter", modelId: "google/gemini-2.5-flash", displayName: "Gemini 2.5 Flash", monthlyTokens: 1000000000, creditTokens: 0, freeType: "recurring-daily", poolKey: "openrouter-free", tos: "ok" },
  { provider: "openrouter", modelId: "deepseek/deepseek-chat-v3-0324:free", displayName: "DeepSeek V3 0324", monthlyTokens: 1000000000, creditTokens: 0, freeType: "recurring-daily", poolKey: "openrouter-free", tos: "ok" },
  { provider: "openrouter", modelId: "deepseek/deepseek-r1-0528:free", displayName: "DeepSeek R1 0528", monthlyTokens: 1000000000, creditTokens: 0, freeType: "recurring-daily", poolKey: "openrouter-free", tos: "ok" },
  { provider: "openrouter", modelId: "meta-llama/llama-4-maverick:free", displayName: "Llama 4 Maverick", monthlyTokens: 1000000000, creditTokens: 0, freeType: "recurring-daily", poolKey: "openrouter-free", tos: "ok" },
  { provider: "openrouter", modelId: "qwen/qwen3-235b-a22b:free", displayName: "Qwen3 235B", monthlyTokens: 1000000000, creditTokens: 0, freeType: "recurring-daily", poolKey: "openrouter-free", tos: "ok" },
  { provider: "openrouter", modelId: "mistralai/mistral-small-3.1-24b-instruct:free", displayName: "Mistral Small 3.1 24B", monthlyTokens: 1000000000, creditTokens: 0, freeType: "recurring-daily", poolKey: "openrouter-free", tos: "ok" },
  { provider: "openrouter", modelId: "microsoft/mai-ds-r1:free", displayName: "MAI DS R1", monthlyTokens: 1000000000, creditTokens: 0, freeType: "recurring-daily", poolKey: "openrouter-free", tos: "ok" },
  { provider: "openrouter", modelId: "moonshotai/kimi-k2:free", displayName: "Kimi K2", monthlyTokens: 1000000000, creditTokens: 0, freeType: "recurring-daily", poolKey: "openrouter-free", tos: "ok" },
  { provider: "openrouter", modelId: "nvidia/llama-3.1-nemotron-ultra-253b-v1:free", displayName: "Nemotron Ultra 253B", monthlyTokens: 1000000000, creditTokens: 0, freeType: "recurring-daily", poolKey: "openrouter-free", tos: "ok" },
  { provider: "mistral", modelId: "mistral-small-latest", displayName: "Mistral Small", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "mistral", modelId: "mistral-medium-latest", displayName: "Mistral Medium", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "mistral", modelId: "codestral-latest", displayName: "Codestral", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "mistral", modelId: "pixtral-large-latest", displayName: "Pixtral Large", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "cloudflare", modelId: "@cf/meta/llama-3.3-70b-instruct-fp8", displayName: "Llama 3.3 70B", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "cloudflare", modelId: "@cf/meta/llama-3.1-8b-instruct-fp8", displayName: "Llama 3.1 8B", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "cloudflare", modelId: "@cf/mistralai/mistral-small-3.1-24b-instruct", displayName: "Mistral Small 3.1", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "cloudflare", modelId: "@cf/deepseek-ai/deepseek-r1-distill-qwen-32b", displayName: "DeepSeek R1 32B", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "cloudflare", modelId: "@cf/qwen/qwen2.5-coder-32b-instruct", displayName: "Qwen2.5 Coder 32B", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "cerebras", modelId: "llama3.3-70b", displayName: "Llama 3.3 70B", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "cerebras", modelId: "llama3.1-8b", displayName: "Llama 3.1 8B", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "cerebras", modelId: "qwen-2.5-32b", displayName: "Qwen 2.5 32B", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "sambanova", modelId: "DeepSeek-V3-0324", displayName: "DeepSeek V3", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "sambanova", modelId: "DeepSeek-R1-Distill-Llama-70B", displayName: "DeepSeek R1 70B", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "sambanova", modelId: "Llama-4-Maverick-17B-128E-Instruct", displayName: "Llama 4 Maverick", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "groq", modelId: "llama-3.3-70b-versatile", displayName: "Llama 3.3 70B", monthlyTokens: 1000000000, creditTokens: 0, freeType: "recurring-monthly", poolKey: "groq-free", tos: "ok" },
  { provider: "groq", modelId: "llama-3.1-8b-instant", displayName: "Llama 3.1 8B Instant", monthlyTokens: 500000000, creditTokens: 0, freeType: "recurring-monthly", poolKey: "groq-free", tos: "ok" },
  { provider: "groq", modelId: "gemma2-9b-it", displayName: "Gemma 2 9B", monthlyTokens: 500000000, creditTokens: 0, freeType: "recurring-monthly", poolKey: "groq-free", tos: "ok" },
  { provider: "huggingface", modelId: "meta-llama/Llama-3.3-70B-Instruct", displayName: "Llama 3.3 70B", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "huggingface", modelId: "Qwen/Qwen2.5-72B-Instruct", displayName: "Qwen 2.5 72B", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "huggingface", modelId: "deepseek-ai/DeepSeek-R1-Distill-Qwen-32B", displayName: "DeepSeek R1 32B", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "huggingface", modelId: "mistralai/Mistral-Small-3.1-24B-Instruct-2503", displayName: "Mistral Small 3.1", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "together", modelId: "meta-llama/Llama-3.3-70B-Instruct-Turbo", displayName: "Llama 3.3 70B Turbo", monthlyTokens: 0, creditTokens: 600000000, freeType: "one-time-initial", poolKey: "together-free", tos: "ok" },
  { provider: "together", modelId: "deepseek-ai/DeepSeek-R1", displayName: "DeepSeek R1", monthlyTokens: 0, creditTokens: 600000000, freeType: "one-time-initial", poolKey: "together-free", tos: "ok" },
  { provider: "together", modelId: "Qwen/Qwen3-235B-A22B-fp8", displayName: "Qwen3 235B", monthlyTokens: 0, creditTokens: 600000000, freeType: "one-time-initial", poolKey: "together-free", tos: "ok" },
  { provider: "nvidia", modelId: "nvidia/llama-3.1-nemotron-ultra-253b-v1", displayName: "Nemotron Ultra 253B", monthlyTokens: 0, creditTokens: 500000000, freeType: "one-time-initial", poolKey: "nvidia-free", tos: "ok" },
  { provider: "nvidia", modelId: "nvidia/llama-3.3-nemotron-super-49b-v1", displayName: "Nemotron Super 49B", monthlyTokens: 0, creditTokens: 500000000, freeType: "one-time-initial", poolKey: "nvidia-free", tos: "ok" },
  { provider: "nvidia", modelId: "deepseek-ai/deepseek-r1", displayName: "DeepSeek R1", monthlyTokens: 0, creditTokens: 500000000, freeType: "one-time-initial", poolKey: "nvidia-free", tos: "ok" },
  { provider: "nvidia", modelId: "meta/llama-3.3-70b-instruct", displayName: "Llama 3.3 70B", monthlyTokens: 0, creditTokens: 500000000, freeType: "one-time-initial", poolKey: "nvidia-free", tos: "ok" },
  { provider: "nvidia", modelId: "qwen/qwen2.5-72b-instruct", displayName: "Qwen 2.5 72B", monthlyTokens: 0, creditTokens: 500000000, freeType: "one-time-initial", poolKey: "nvidia-free", tos: "ok" },
  { provider: "pollinations", modelId: "openai", displayName: "OpenAI (via Pollinations)", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "pollinations", modelId: "openai-fast", displayName: "OpenAI Fast", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "pollinations", modelId: "openai-large", displayName: "OpenAI Large", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "pollinations", modelId: "deepseek", displayName: "DeepSeek", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "pollinations", modelId: "deepseek-reasoning", displayName: "DeepSeek Reasoning", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "pollinations", modelId: "gemini", displayName: "Gemini", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "pollinations", modelId: "gemini-thinking", displayName: "Gemini Thinking", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "pollinations", modelId: "mistral", displayName: "Mistral", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "pollinations", modelId: "qwen", displayName: "Qwen", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "chutes", modelId: "deepseek-ai/DeepSeek-R1", displayName: "DeepSeek R1", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "chutes", modelId: "deepseek-ai/DeepSeek-V3-0324", displayName: "DeepSeek V3", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "chutes", modelId: "Qwen/Qwen3-235B-A22B", displayName: "Qwen3 235B", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "chutes", modelId: "meta-llama/Llama-4-Maverick-17B-128E-Instruct", displayName: "Llama 4 Maverick", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "chutes", modelId: "moonshotai/Kimi-K2-Instruct", displayName: "Kimi K2", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "chutes", modelId: "microsoft/MAI-DS-R1", displayName: "MAI DS R1", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "aimlapi", modelId: "meta-llama/Llama-3.3-70B-Instruct", displayName: "Llama 3.3 70B", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "aimlapi", modelId: "mistralai/Mistral-Small-3.1-24B-Instruct-2503", displayName: "Mistral Small 3.1", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "aimlapi", modelId: "Qwen/Qwen3-235B-A22B", displayName: "Qwen3 235B", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "aimlapi", modelId: "google/gemma-3-27b-it", displayName: "Gemma 3 27B", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "xai", modelId: "grok-3-mini", displayName: "Grok 3 Mini", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "volcengine", modelId: "doubao-1.5-pro-32k", displayName: "Doubao 1.5 Pro 32K", monthlyTokens: 500000000, creditTokens: 0, freeType: "recurring-monthly", poolKey: "volcengine-free", tos: "ok" },
  { provider: "volcengine", modelId: "doubao-1.5-lite-32k", displayName: "Doubao 1.5 Lite 32K", monthlyTokens: 500000000, creditTokens: 0, freeType: "recurring-monthly", poolKey: "volcengine-free", tos: "ok" },
  { provider: "volcengine", modelId: "deepseek-v3-250324", displayName: "DeepSeek V3", monthlyTokens: 500000000, creditTokens: 0, freeType: "recurring-monthly", poolKey: "volcengine-free", tos: "ok" },
  { provider: "volcengine", modelId: "deepseek-r1-250528", displayName: "DeepSeek R1", monthlyTokens: 500000000, creditTokens: 0, freeType: "recurring-monthly", poolKey: "volcengine-free", tos: "ok" },
  { provider: "baidu", modelId: "ernie-4.5-8k", displayName: "ERNIE 4.5 8K", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "baidu", modelId: "ernie-4.5-128k", displayName: "ERNIE 4.5 128K", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "alibaba", modelId: "qwen-plus", displayName: "Qwen Plus", monthlyTokens: 0, creditTokens: 1000000000, freeType: "one-time-initial", poolKey: "alibaba-free", tos: "ok" },
  { provider: "alibaba", modelId: "qwen-turbo", displayName: "Qwen Turbo", monthlyTokens: 0, creditTokens: 1000000000, freeType: "one-time-initial", poolKey: "alibaba-free", tos: "ok" },
  { provider: "alibaba", modelId: "qwen3-235b-a22b", displayName: "Qwen3 235B", monthlyTokens: 0, creditTokens: 1000000000, freeType: "one-time-initial", poolKey: "alibaba-free", tos: "ok" },
  { provider: "alibaba", modelId: "qwen-long", displayName: "Qwen Long", monthlyTokens: 0, creditTokens: 1000000000, freeType: "one-time-initial", poolKey: "alibaba-free", tos: "ok" },
  { provider: "zhipu", modelId: "glm-4-flash", displayName: "GLM 4 Flash", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "zhipu", modelId: "glm-4v-flash", displayName: "GLM 4V Flash", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "zhipu", modelId: "glm-z1-air", displayName: "GLM Z1 Air", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "zhipu", modelId: "glm-z1-airx", displayName: "GLM Z1 AirX", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "moonshot", modelId: "moonshot-v1-8k", displayName: "Moonshot V1 8K", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "siliconflow", modelId: "deepseek-ai/DeepSeek-V3", displayName: "DeepSeek V3", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "siliconflow", modelId: "deepseek-ai/DeepSeek-R1", displayName: "DeepSeek R1", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "siliconflow", modelId: "Qwen/Qwen3-235B-A22B", displayName: "Qwen3 235B", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "siliconflow", modelId: "Qwen/Qwen2.5-7B-Instruct", displayName: "Qwen 2.5 7B", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "novita", modelId: "deepseek/deepseek-r1", displayName: "DeepSeek R1", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "novita", modelId: "deepseek/deepseek-chat-v3-0324", displayName: "DeepSeek V3", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "novita", modelId: "meta-llama/llama-4-maverick-17b-128e-instruct", displayName: "Llama 4 Maverick", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "hyperbolic", modelId: "meta-llama/Llama-3.3-70B-Instruct", displayName: "Llama 3.3 70B", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "hyperbolic", modelId: "deepseek-ai/DeepSeek-R1", displayName: "DeepSeek R1", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "fireworks", modelId: "accounts/fireworks/models/deepseek-v3-0324", displayName: "DeepSeek V3", monthlyTokens: 0, creditTokens: 100000000, freeType: "one-time-initial", poolKey: "fireworks-free", tos: "ok" },
  { provider: "fireworks", modelId: "accounts/fireworks/models/llama-v3p3-70b-instruct", displayName: "Llama 3.3 70B", monthlyTokens: 0, creditTokens: 100000000, freeType: "one-time-initial", poolKey: "fireworks-free", tos: "ok" },
  { provider: "fireworks", modelId: "accounts/fireworks/models/qwen3-235b-a22b", displayName: "Qwen3 235B", monthlyTokens: 0, creditTokens: 100000000, freeType: "one-time-initial", poolKey: "fireworks-free", tos: "ok" },
  { provider: "yi", modelId: "yi-lightning", displayName: "Yi Lightning", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "yi", modelId: "yi-large", displayName: "Yi Large", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "targon", modelId: "deepseek-ai/DeepSeek-R1", displayName: "DeepSeek R1", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "targon", modelId: "moonshotai/Kimi-K2-Instruct", displayName: "Kimi K2", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "targon", modelId: "Qwen/Qwen3-235B-A22B", displayName: "Qwen3 235B", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "nebius", modelId: "meta-llama/Llama-3.3-70B-Instruct-fast", displayName: "Llama 3.3 70B", monthlyTokens: 0, creditTokens: 1000000000, freeType: "one-time-initial", poolKey: "nebius-free", tos: "ok" },
  { provider: "nebius", modelId: "deepseek-ai/DeepSeek-V3-0324", displayName: "DeepSeek V3", monthlyTokens: 0, creditTokens: 1000000000, freeType: "one-time-initial", poolKey: "nebius-free", tos: "ok" },
  { provider: "featherless", modelId: "meta-llama/Llama-3.3-70B-Instruct", displayName: "Llama 3.3 70B", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "featherless", modelId: "deepseek-ai/DeepSeek-R1-Distill-Qwen-32B", displayName: "DeepSeek R1 32B", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "featherless", modelId: "Qwen/Qwen3-235B-A22B", displayName: "Qwen3 235B", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "unify", modelId: "llama-3.3-70b@nebius", displayName: "Llama 3.3 70B", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
  { provider: "unify", modelId: "deepseek-v3-0324@nebius", displayName: "DeepSeek V3", monthlyTokens: 0, creditTokens: 0, freeType: "recurring-uncapped", poolKey: null, tos: "ok" },
];
