export default {
  id: "digitalocean",
  priority: 100,
  alias: "do",
  uiAlias: "do",
  display: {
    name: "DigitalOcean",
    icon: "cloud",
    color: "#0069FF",
    textIcon: "DO",
    website: "https://www.digitalocean.com",
    notice: {
      apiKeyUrl: "https://cloud.digitalocean.com/account/api/tokens",
    },
  },
  category: "apikey",
  authModes: ["apikey"],
  transport: {
    baseUrl: "https://inference.do-ai.run/v1/chat/completions",
    format: "openai",
    auth: {
      header: "Authorization",
      scheme: "bearer",
    },
  },
  models: [
    { id: "alibaba-qwen3-32b", name: "Alibaba Qwen3 32B" },
    { id: "anthropic-claude-4.1-opus", name: "Claude 4.1 Opus" },
    { id: "anthropic-claude-4.5-sonnet", name: "Claude 4.5 Sonnet" },
    { id: "anthropic-claude-4.6-sonnet", name: "Claude 4.6 Sonnet" },
    { id: "anthropic-claude-5-sonnet", name: "Claude 5 Sonnet" },
    { id: "anthropic-claude-fable-5", name: "Claude Fable 5" },
    { id: "anthropic-claude-haiku-4.5", name: "Claude Haiku 4.5" },
    { id: "anthropic-claude-opus-4.5", name: "Claude Opus 4.5" },
    { id: "anthropic-claude-opus-4.6", name: "Claude Opus 4.6" },
    { id: "anthropic-claude-opus-4.7", name: "Claude Opus 4.7" },
    { id: "anthropic-claude-opus-4.8", name: "Claude Opus 4.8" },
    { id: "arcee-trinity-large-thinking", name: "Arcee Trinity Large Thinking" },
    { id: "deepseek-3.2", name: "DeepSeek 3.2" },
    { id: "deepseek-4-flash", name: "DeepSeek 4 Flash" },
    { id: "deepseek-r1-distill-llama-70b", name: "DeepSeek R1 Distill Llama 70B" },
    { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "gemma-4-31B-it", name: "Gemma 4 31B IT" },
    { id: "glm-5", name: "GLM 5" },
    { id: "glm-5.1", name: "GLM 5.1" },
    { id: "glm-5.2", name: "GLM 5.2" },
    { id: "kimi-k2.5", name: "Kimi K2.5" },
    { id: "kimi-k2.6", name: "Kimi K2.6" },
    { id: "llama-4-maverick", name: "Llama 4 Maverick" },
    { id: "llama3.3-70b-instruct", name: "Llama 3.3 70B Instruct" },
    { id: "mimo-v2.5", name: "Mimo V2.5" },
    { id: "mimo-v2.5-pro", name: "Mimo V2.5 Pro" },
    { id: "minimax-m2.5", name: "MiniMax M2.5" },
    { id: "mistral-3-14B", name: "Mistral 3 14B" },
    { id: "nemotron-3-nano-omni", name: "Nemotron 3 Nano Omni" },
    { id: "nemotron-3-ultra-550b", name: "Nemotron 3 Ultra 550B" },
    { id: "nemotron-nano-12b-v2-vl", name: "Nemotron Nano 12B V2 VL" },
    { id: "nvidia-nemotron-3-super-120b", name: "NVIDIA Nemotron 3 Super 120B" },
    { id: "openai-gpt-4.1", name: "GPT-4.1" },
    { id: "openai-gpt-4o", name: "GPT-4o" },
    { id: "openai-gpt-4o-mini", name: "GPT-4o Mini" },
    { id: "openai-gpt-5", name: "GPT-5" },
    { id: "openai-gpt-5-mini", name: "GPT-5 Mini" },
    { id: "openai-gpt-5-nano", name: "GPT-5 Nano" },
    { id: "openai-gpt-5.1-codex-max", name: "GPT-5.1 Codex Max" },
    { id: "openai-gpt-5.2", name: "GPT-5.2" },
    { id: "openai-gpt-5.2-pro", name: "GPT-5.2 Pro" },
    { id: "openai-gpt-5.3-codex", name: "GPT-5.3 Codex" },
    { id: "openai-gpt-5.4", name: "GPT-5.4" },
    { id: "openai-gpt-5.4-mini", name: "GPT-5.4 Mini" },
    { id: "openai-gpt-5.4-nano", name: "GPT-5.4 Nano" },
    { id: "openai-gpt-5.4-pro", name: "GPT-5.4 Pro" },
    { id: "openai-gpt-5.5", name: "GPT-5.5" },
    { id: "openai-gpt-5.6-luna", name: "GPT-5.6 Luna" },
    { id: "openai-gpt-5.6-sol", name: "GPT-5.6 Sol" },
    { id: "openai-gpt-5.6-terra", name: "GPT-5.6 Terra" },
    { id: "openai-gpt-image-1", name: "GPT Image 1", type: "image" },
    { id: "openai-gpt-image-1.5", name: "GPT Image 1.5", type: "image" },
    { id: "openai-gpt-image-2", name: "GPT Image 2", type: "image" },
    { id: "openai-gpt-oss-120b", name: "GPT OSS 120B" },
    { id: "openai-gpt-oss-20b", name: "GPT OSS 20B" },
    { id: "openai-o1", name: "OpenAI o1" },
    { id: "openai-o3", name: "OpenAI o3" },
    { id: "openai-o3-mini", name: "OpenAI o3 Mini" },
    { id: "qwen3-coder-flash", name: "Qwen3 Coder Flash" },
    { id: "qwen3.5-397b-a17b", name: "Qwen3.5 397B A17B" },
    { id: "stable-diffusion-3.5-large", name: "Stable Diffusion 3.5 Large", type: "image" },
    { id: "wan2-2-t2v-a14b", name: "Wan2.2 T2V A14B", type: "video" },
  ],
  serviceKinds: ["llm"],
  passthroughModels: true,
};
