export default {
  id: "opencode",
  priority: 40,
  hasFree: true,
  alias: "oc",
  uiAlias: "oc",
  display: {
    name: "OpenCode Free",
    icon: "terminal",
    color: "#E87040",
    textIcon: "OC",
  },
  category: "free",
  noAuth: true,
  transport: {
    baseUrl: "https://opencode.ai",
    headers: {
      "x-opencode-client": "desktop",
    },
    noAuth: true,
  },
  models: [    { id: "big-pickle", name: "Big Pickle" },
    { id: "deepseek-v4-flash-free", name: "DeepSeek V4 Flash Free" },
    { id: "minimax-m2.5-free", name: "MiniMax M2.5 Free" },
    { id: "ling-2.6-1t-free", name: "Ling 2.6 Free" },
    { id: "trinity-large-preview-free", name: "Trinity Large Preview Free" },
    { id: "nemotron-3-super-free", name: "Nemotron 3 Super Free" },
    { id: "qwen3.6-plus-free", name: "Qwen3.6 Plus Free" },
],
  modelsFetcher: { url: "https://opencode.ai/zen/v1/models", type: "opencode-free" },
  passthroughModels: true,
};
